PASSWD_LEN = 16  # 密码长度
ACS_CARD_NO_LEN = 32
NAME_LEN = 32
NET_SDK_MONITOR_ID_LEN = 64
NET_SDK_EMPLOYEE_NO_LEN = 32
NET_DVR_GET_ACS_EVENT = 2514
MAX_NAMELEN = 16
MAX_DOOR_NUM_256 = 256
MAX_GROUP_NUM_128 = 128
CARD_PASSWORD_LEN = 8
MAX_CARD_RIGHT_PLAN_NUM = 4
MAX_LOCK_CODE_LEN = 8
MAX_DOOR_CODE_LEN = 8
MAX_CARD_READER_NUM_512 = 512
MAX_FINGER_PRINT_LEN = 768
MAX_FINGER_PRINT_NUM = 10
MAX_FACE_NUM = 2

NET_SDK_CALLBACK_STATUS_SUCCESS = 1000        # 成功
NET_SDK_CALLBACK_STATUS_PROCESSING = 1001            # 处理中
NET_SDK_CALLBACK_STATUS_FAILED = 1002                # 失败
NET_SDK_CALLBACK_STATUS_EXCEPTION = 1003            # 异常
NET_SDK_CALLBACK_STATUS_LANGUAGE_MISMATCH = 1004    #（IPC配置文件导入）语言不匹配
NET_SDK_CALLBACK_STATUS_DEV_TYPE_MISMATCH = 1005    #（IPC配置文件导入）设备类型不匹配
NET_DVR_CALLBACK_STATUS_SEND_WAIT = 1006           # 发送等待

NET_DVR_GET_CARD = 2560
NET_DVR_SET_CARD = 2561
NET_DVR_GET_FINGERPRINT = 2563
NET_DVR_SET_FINGERPRINT = 2564
NET_DVR_GET_FACE = 2566
NET_DVR_SET_FACE = 2567

NET_DVR_JSON_CONFIG = 2550

ERROR_MSG_LEN = 32
