# MySQL
mysql:
  host: 'localhost'
  password: '123456'
#  host: '39.108.137.187'
#  password: 'QQ23ti!#'
  port: 3306
  user: 'sa'
  database: 'tool_manage_sys'
  charset: 'utf8mb4'

# for InfluxDB
influxdb:
  host: 'localhost'
  port: 8086
  username: 'sa'
  password: '123456'
  database: 'iiot_sys'
  use_udp: True
  udp_port: 4444


# for RabbitMQ
rabbitmq:
  host: 'localhost'
  username: 'Alex'
  pwd: 'Alex11235813'


# for Redis
redis:
  host: 'localhost'
  port: 6379
  db: 1
  max_conn: 100


# for log
log:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    info_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: simple
      filename: ./logs/info.log
      when: midnight
      backupCount: 20
      encoding: utf8
      filters:
      - filter_by_name
    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: simple
      filename: ./logs/errors.log
      maxBytes: 10485760
      backupCount: 20
      encoding: utf8
  filters:
    filter_by_name:
      class: logging.Filter
      name: root
  loggers:
    my_module:
      level: INFO
      handlers:
      - info_file_handler
      - error_file_handler
      propagate: no
  root:
    level: INFO
    handlers:
    - info_file_handler
    - error_file_handler