# MySQL
mysql:
#  host: 'localhost'
#  password: '123456'
#  user: 'sa'
  host: '192.168.1.155'
  password: '!QAZ2wsx3edc'
  user: 'root'
  port: 3306
  database: 'tool_manage_sys'
  charset: 'utf8mb4'


# for Redis
redis:
  host: 'localhost'
  port: 6379
  db: 1
  max_conn: 100


# for log
log:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    info_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: simple
      filename: ./logs/info.log
      when: midnight
      backupCount: 20
      encoding: utf8
      filters:
      - filter_by_name
    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: simple
      filename: ./logs/errors.log
      maxBytes: 10485760
      backupCount: 20
      encoding: utf8
  filters:
    filter_by_name:
      class: logging.Filter
      name: root
  loggers:
    my_module:
      level: INFO
      handlers:
      - info_file_handler
      - error_file_handler
      propagate: no
  root:
    level: INFO
    handlers:
    - info_file_handler
    - error_file_handler


# for configuration
configuration:
  gateway_server_check_interval: 1  # seconds
  gravity_precision: 10  # g
  gravity_update_interval: 10  # seconds, it must greater than 5s
  r2000fh_update_interval: 5   # seconds, it must greater than 5s
  cm_r2000fh_update_interval: 5  # seconds, it must greater than 5s
  hkvision_user_update_interval: 10  # seconds
  storeroom_close_delay_time: 60  # seconds
